name: pip_audit

on: [push]

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install pip-audit
        run: pip install pip-audit

      - name: Run audit
        run: pip-audit -r requirements.txt --strict
