name: pip_audit

on: [push]

jobs:
  audit:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - run: pip install -r requirements2.txt

      - run: pip install pip-audit

      - run: pip-audit -r requirements2.txt --strict
